spring:
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration

server:
  port: 8080

app:
  name: Venue Catalog - Dev Profile
  environment: Desarrollo

logging:
  level:
    root: INFO
    org.springframework.web: DEBUG
  file:
    name: logs/dev-app.log
